### ISSUE TITLE
Feedback on ch01-the-command-line.ipynb

### ISSUE THREAD

**Issue by ttimbers** [physics-codes/seminar#3]
@katyhuff @scopatz I have started writing the code from the book (I also added a few more explicit examples where I thought it might be helpful) and annotating it for Chapter 1, the command line. The ipynb is [here](https://github.com/physics-codes/seminar/blob/ch01/ch01-the-command-line.ipynb) and I'd appreciate feedback on it (content, style, verbosity, etc) before I dig in much further, to make sure I'm not straying too far away from what we talked about. Thanks!!

**Comment by katyhuff** [comment]
Hi @ttimbers Thanks! I think this looks good, personally, but it definitely does follow the book text very closely. (I'm not sure what else should be done... will the students have copies of the book?) 

I'd like @scopatz to make sure it doesn't violate any of our rules about copy/pasting from the book. @scopatz, does this replicate the book too closely? What are the rules about that?

Also, @ttimbers , you won't have to create a separate 'review this change' issue in the future if  you issue changes as pull requests instead. That is, if changes are made as pull requests, everything will necessarily be reviewed during the pull request before we pull it in. I'll do the same thing, so that you see the changes that I make also.

**Comment by katyhuff** [comment]
(I think it's great though. no changes needed, IMHO... as long as the legality is cool. )

**Comment by scopatz** [comment]
Hi both. To me (though I am not O'Reilly or a lawyer) this violates the spirit of the copyright, if not the actual copyright.  The copyright allows for verbatim copies of the codes samples - these are effectively open.  However, the text of the book (the non-code sample part) is treated the same as any other creative publication (ie not free). What is here seems to be a condensed, and thus derivative, work for which the original copyright and any licensing agreements apply. If you want to do this, you really have to talk to O'Reilly since they are responsible for licensing and defending Katy's and my copyright.

Also, conceptually, I am not sure how valuable a condensed book is. The purpose of a course is to show the same things in many ways (so that it really sinks in). One of those ways is the notes and the other is the reading material.

Some topical changes could make this palatable.
- Don't have the heading be exactly the same and/or in the same order
- Change the examples and (more importantly) the exercises, even in minor ways (like variable names where you can, people's names)
- Cut things out ruthlessly, you have much less space and time in a course than in book.

It is highly desirable to use the book as a closely followed guide. There should be a clear line from what is in the course to what is in the book. However, even if only for copyright reasons, it shouldn't be redundant.  If you'd like me to check with O'Reilly on what _exactly_ the rules are here, I'd be happy to do so. Just let me know.

Thanks again for being the forger-aheader, @ttimbers :).

**Comment by katyhuff** [comment]
That's helpful. As does @scopatz, I did somewhat envision that the
notebooks or notes in the seminar materials might be more like a "guided
tour" through the chapters and examples, rather than a replication.
However, unlike @scopatz, I do feel like it's probably ok to go through the
exercises as they exist in the book (they're already in the examples repo,
after all). For my purposes, I would rather all of the in-class examples to
be applied to the project at hand though. That may not be possible upon
first introduction of the concepts, but definitely would be possible at the
end of the class. For one class session, that might look like:

Pre-Class-Homework:
Read pages X through Y in the book.

Main Topic Heading:
Sentence introducing topic. (As an instructor, take this moment to verbally
summarize pages X through Y. Use the book as notes.)

Definitions:
Select a few keywords from the chapter. Ask the students to fill in their
definitions while you lecture? They should save their notebook at the end
of class. It becomes _their_ version of the lecture notes. Perhaps it could
be turned in for points.

Exercise 1:
Provide the instructions presented in the book exercise. Set up the problem
(perform the first step, for example), and then leave an open space for the
students to finish the steps in that example.

SubTopic:
Sentence introducing the subtopic. (As an instructor, take this moment to
verbally summarize the subtopic. Use the book as notes.)

Exercise 2:
Provide the instructions presented in the book exercise. Set up the problem
(perform the first step, for example), and then leave an open space for the
students to finish the steps in that example.

etc....

Group Exercise:
Apply what we learned today to your individual or group project. Do files
need to be found?  Do repositories need to be created? Does a git issue
need to be made? Should the students implement a loop? a class?

Homework:
Read pages Y through Z in the book.

On Mon, Oct 12, 2015 at 1:05 PM, Anthony Scopatz notifications@github.com
wrote:

> Hi both. To me (though I am not O'Reilly or a lawyer) this violates the
> spirit of the copyright, if not the actual copyright. The copyright allows
> for verbatim copies of the codes samples - these are effectively open.
> However, the text of the book (the non-code sample part) is treated the
> same as any other creative publication (ie not free). What is here seems to
> be a condensed, and thus derivative, work for which the original copyright
> and any licensing agreements apply. If you want to do this, you really have
> to talk to O'Reilly since they are responsible for licensing and defending
> Katy's and my copyright.
> 
> Also, conceptually, I am not sure how valuable a condensed book is. The
> purpose of a course is to show the same things in many ways (so that it
> really sinks in). One of those ways is the notes and the other is the
> reading material.
> 
> Some topical changes could make this palatable.
> - Don't have the heading be exactly the same and/or in the same order
> - Change the examples and (more importantly) the exercises, even in
>   minor ways (like variable names where you can, people's names)
> - Cut things out ruthlessly, you have much less space and time in a
>   course than in book.
> 
> It is highly desirable to use the book as a closely followed guide. There
> should be a clear line from what is in the course to what is in the book.
> However, even if only for copyright reasons, it shouldn't be redundant. If
> you'd like me to check with O'Reilly on what _exactly_ the rules are
> here, I'd be happy to do so. Just let me know.
> 
> Thanks again for being the forger-aheader, @ttimbers
> https://github.com/ttimbers :).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/physics-codes/seminar/issues/3#issuecomment-147505458
> .

## 

http://katyhuff.github.com

**Comment by ttimbers** [comment]
@scopatz @katyhuff Thank-you very much for the  thoughtful feedback. I do agree that these could be made even more concise, and do not have to cover all of the textbook content - you're right that trying to go through the entire textbook during lecture would not work, there simply is not enough time. 

@scopatz I hear your copyright concerns, but I am not sure that we are violating copyright if these notebooks are to be used in a classroom that adopts your textbook. I could not find the documentation for O'Reilly, but it appears that both [Pearson and Wiley allow course instructors who have adopted a textbook for a class to reproduce copyrighted textbook content items, including images, art, solutions/answers, test questions, _etc_. These are expected to be used in a limited fashion for educational purposes including presentation material in your classroom lectures](http://copyright.ubc.ca/guidelines-and-resources/faq/instructor-faq/#2.18_I_adopted_a_textbook_for_my_course.2C_and_the_book_representative_gave_me_instructional_materials.2C_including_images.2C_PowerPoint_files.2C_etc._Can_I_distribute_any_of_those_materials_to_my_students_on_paper_or_in_my_UBC_learning_or_course_management_system.3F). Thus, I expect O'Reilly would be along similar lines.

If we generalize what Pearson and Wiley do (see above) to O'Reilly, then I guess it depends on how these .ipynb's are intended to be used and shared. If we attach a statement in the README that these are to only be used as classroom material in classes that adopt your textbook, then I think we are fine. Maybe they could be distributed with the textbook as instructor support materials? I have seen this with other textbooks. But yes, @scopatz I still would like to know more from O'Reilly about what I can and can't do with the textbook material. I don't want to get myself into any trouble :)

On teaching content note - as an instructor, I am not very motivated to use a textbook that I use only to assign readings to students, and then have to come up with all my own additional content and exercises for use in the classroom. In other courses I have taken and taught, I think it is very common for instructors to use textbook material directly from the book in class (e.g., figures from textbooks in lectures) as well as use questions directly from the textbook. 

I guess my vision for teaching the course was to work through your textbook content and examples with the students in class and give them lots of other challenges. The out of class assignments would then be applying what was covered in class on their own project. I will also be making 5 or 6 quizzes that students will do in class, and these would be on the same content as the book but using different data examples.

As I mentioned above, one thing I can definitely do is add additional exercises to the .ipynb's. I really find that most students learn by doing, and so I would like them to spend as much time doing in the classroom as possible.

**Comment by katyhuff** [comment]
@ttimbers - - I also would love to see you use the examples from the
textbook, as is.

I think your vision sounds great ("work through your textbook content and
examples with the students in class and give them lots of other
challenges.")  In particular, I definitely support you in using the
textbook questions/exercises directly. I think the copyright mostly gets
hairy when there's a lot of text copy/pasting. Ideally, students and
instructors alike can refer to the text for that discussion.

@scopatz -- since the value of the book, for instructors, lies in the work
we've already done to create the exercises, do you think it would be ok for
the exercises to be copied explicitly in the ipython notebooks? I don't see
much difference between this and having the examples repository, except
this is easier to use and adopt.

Maybe the solution is just to limit the amount of words/text in the
notebooks, leaving the exercises as they are. If additional exercises can
be added, then that's great, but not necessary, as ideally this would be a
generic set of notebooks for instructors to use and add to on their own.

Thoughts on that @scopatz?

On Mon, Oct 12, 2015 at 2:27 PM, Tiffany Timbers notifications@github.com
wrote:

> @scopatz https://github.com/scopatz @katyhuff
> https://github.com/katyhuff Thank-you very much for the thoughtful
> feedback. I do agree that these could be made even more concise, and do not
> have to cover all of the textbook content - you're right that trying to go
> through the entire textbook during lecture would not work, there simply is
> not enough time.
> 
> @scopatz https://github.com/scopatz I hear your copyright concerns, but
> I am not sure that we are violating copyright if these notebooks are to be
> used in a classroom that adopts your textbook. I could not find the
> documentation for O'Reilly, but it appears that both Pearson and Wiley
> allow course instructors who have adopted a textbook for a class to
> reproduce copyrighted textbook content items, including images, art,
> solutions/answers, test questions, _etc_. These are expected to be used
> in a limited fashion for educational purposes including presentation
> material in your classroom lectures
> http://copyright.ubc.ca/guidelines-and-resources/faq/instructor-faq/#2.18_I_adopted_a_textbook_for_my_course.2C_and_the_book_representative_gave_me_instructional_materials.2C_including_images.2C_PowerPoint_files.2C_etc._Can_I_distribute_any_of_those_materials_to_my_students_on_paper_or_in_my_UBC_learning_or_course_management_system.3F.
> T hus, I expect O'Reilly would be along similar lines.
> 
> If we generalize what Pearson and Wiley do (see above) to O'Reilly, then I
> guess it depends on how these .ipynb's are intended to be used and shared.
> If we attach a statement in the README that these are to only be used as
> classroom material in classes that adopt your textbook, then I think we are
> fine. Maybe they could be distributed with the textbook as instructor
> support materials? I have seen this with other textbooks. But yes,
> @scopatz https://github.com/scopatz I still would like to know more
> from O'Reilly about what I can and can't do with the textbook material. I
> don't want to get myself into any trouble :)
> 
> On teaching content note - as an instructor, I am not very motivated to
> use a textbook that I use only to assign readings to students, and then
> have to come up with all my own additional content and exercises for use in
> the classroom. In other courses I have taken and taught, I think it is very
> common for instructors to use textbook material directly from the book in
> class (e.g., figures from textbooks in lectures) as well as use questions
> directly from the textbook.
> 
> I guess my vision for teaching the course was to work through your
> textbook content and examples with the students in class and give them lots
> of other challenges. The out of class assignments would then be applying
> what was covered in class on their own project. I will also be making 5 or
> 6 quizzes that students will do in class, and these would be on the same
> content as the book but using different data examples.
> 
> As I mentioned above, one thing I can definitely do is add additional
> exercises to the .ipynb's. I really find that most students learn by doing,
> and so I would like them to spend as much time doing in the classroom as
> possible.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/physics-codes/seminar/issues/3#issuecomment-147526975
> .

## 

http://katyhuff.github.com

**Comment by scopatz** [comment]
For posterity here, I have sent a email off to O'Reilly. We really need direct clarification from them at this point.

**Comment by katyhuff** [comment]
I think this is now closed. O'Reilly says we can reuse up to 10% of the book in this context.
